Update NVFLARE to 2.4.2
This is required to fix the NVFLARE provisioning issue:

AttributeError: module 'cryptography.hazmat.primitives.serialization' has no attribute 'pkcs12'

Signed-off-by: Arun Patole <apatole@nvidia.com>